spring:
  application:
    name: gateway

  config:
    #    config server host
    import: optional:configserver:http://localhost:8082


  profiles:
    active: test
#    active: ${setting.profile.type}

