spring:
  application:
    name: eureka

server:
  port: 8081


# Eureka ??? client? ???? ?? ??? false ??
eureka:
  server:
    enable-self-preservation: true
  client:
    # ?????? ??? ????? ?? ??
    register-with-eureka: false
    # Eureka????? ?????? ??? ????? ??? ???? ??
    fetch-registry: false
